// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Reservas.Domain.Entites;
using Reservas.Domain.Entities;

namespace Reservas.Persistence.Data;

public partial class BarceloReservasContext : DbContext
{
    public BarceloReservasContext(DbContextOptions<BarceloReservasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActividadesRecreativa> ActividadesRecreativas { get; set; }

    public virtual DbSet<Reserva> Reservas { get; set; }

    public virtual DbSet<Hotel> Hoteles { get; set; }

    public virtual DbSet<ActividadesRecreativa> ReservasActividades { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

        OnModelCreatingPartial(modelBuilder);

        modelBuilder.ApplyConfigurationsFromAssembly(
            typeof(BarceloReservasContext).Assembly
        );

    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}