// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Dispositivos.Domain.Entities;
using Dispositivos.Persistence.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Dispositivos.Persistence.Data.Configurations
{
    public partial class CerradurasInteligenteConfiguration : IEntityTypeConfiguration<CerradurasInteligente>
    {
        public void Configure(EntityTypeBuilder<CerradurasInteligente> entity)
        {
            entity.HasKey(e => e.CerraduraId);

            entity.HasIndex(e => e.DispositivoId, "IX_Cerraduras_DispositivoId");

            entity.HasIndex(e => new { e.EstadoPuerta, e.EstaActiva }, "IX_Cerraduras_EstadoPuerta");

            entity.HasIndex(e => e.HabitacionId, "IX_Cerraduras_HabitacionId");

            entity.HasIndex(e => e.HabitacionId, "UQ_Cerraduras_Habitacion").IsUnique();

            entity.Property(e => e.EstaActiva).HasDefaultValue(true);
            entity.Property(e => e.EstadoPuerta)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Cerrada");
            entity.Property(e => e.FechaActivacion).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.SoportaModoOffline).HasDefaultValue(true);

            entity.HasOne(d => d.Dispositivo).WithMany(p => p.CerradurasInteligentes)
                .HasForeignKey(d => d.DispositivoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cerraduras_Dispositivos");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CerradurasInteligente> entity);
    }
}
