// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Dispositivos.Persistence.Models;
using Microsoft.EntityFrameworkCore;
using Dispositivos.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Dispositivos.Persistence.Models.Configurations
{
    public partial class CredencialesAccesoConfiguration : IEntityTypeConfiguration<CredencialesAcceso>
    {
        public void Configure(EntityTypeBuilder<CredencialesAcceso> entity)
        {
            entity.HasKey(e => e.CredencialId);

            entity.ToTable("CredencialesAcceso");

            entity.HasIndex(e => new { e.EstaActiva, e.FechaExpiracion }, "IX_Credenciales_Activas").HasFilter("([EstaActiva]=(1))");

            entity.HasIndex(e => e.HuespedId, "IX_Credenciales_HuespedId").HasFilter("([HuespedId] IS NOT NULL)");

            entity.HasIndex(e => e.PersonalId, "IX_Credenciales_PersonalId").HasFilter("([PersonalId] IS NOT NULL)");

            entity.Property(e => e.CodigoPin)
                .IsRequired()
                .HasMaxLength(6)
                .HasColumnName("CodigoPIN");
            entity.Property(e => e.CreadoPor).HasMaxLength(450);
            entity.Property(e => e.EstaActiva).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.HashPin)
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnName("HashPIN");
            entity.Property(e => e.TipoCredencial)
                .IsRequired()
                .HasMaxLength(30);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CredencialesAcceso> entity);
    }
}
