// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Dispositivos.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Dispositivos.Persistence.Data.Configurations
{
    public partial class DispositivoConfiguration : IEntityTypeConfiguration<Dispositivo>
    {
        public void Configure(EntityTypeBuilder<Dispositivo> entity)
        {
            entity.HasIndex(e => new { e.NivelBateria, e.EstaEnLinea }, "IX_Dispositivos_EstadoBateria").HasFilter("([NivelBateria]<(30))");

            entity.HasIndex(e => e.HotelId, "IX_Dispositivos_HotelId");

            entity.HasIndex(e => e.NumeroSerieDispositivo, "IX_Dispositivos_NumeroSerie");

            entity.HasIndex(e => new { e.TipoDispositivo, e.EstadoFuncional }, "IX_Dispositivos_TipoDispositivo");

            entity.HasIndex(e => e.DireccionMac, "UQ_Dispositivos_MAC").IsUnique();

            entity.HasIndex(e => e.NumeroSerieDispositivo, "UQ_Dispositivos_NumeroSerie").IsUnique();

            entity.Property(e => e.DireccionMac)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("DireccionMAC");
            entity.Property(e => e.EstaEnLinea).HasDefaultValue(true);
            entity.Property(e => e.EstadoFuncional)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Operativo");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.FechaInstalacion).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Ipdispositivo)
                .HasMaxLength(50)
                .HasColumnName("IPDispositivo");
            entity.Property(e => e.Modelo).HasMaxLength(100);
            entity.Property(e => e.NivelBateria).HasDefaultValue(100);
            entity.Property(e => e.NumeroSerieDispositivo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TipoDispositivo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.VersionFirmware)
                .IsRequired()
                .HasMaxLength(20);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Dispositivo> entity);
    }
}
