// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Dispositivos.Persistence.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using Dispositivos.Domain.Entities;
using System.Collections.Generic;

namespace Dispositivos.Persistence.Data.Configurations
{
    public partial class MantenimientoCerraduraConfiguration : IEntityTypeConfiguration<MantenimientoCerradura>
    {
        public void Configure(EntityTypeBuilder<MantenimientoCerradura> entity)
        {
            entity.HasKey(e => e.MantenimientoId);

            entity.Property(e => e.CostoMantenimiento).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("Programado");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Observaciones).HasMaxLength(1000);
            entity.Property(e => e.TipoMantenimiento)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Cerradura).WithMany(p => p.MantenimientoCerraduras)
                .HasForeignKey(d => d.CerraduraId)
                .HasConstraintName("FK_Mantenimiento_Cerraduras");

            entity.HasOne(d => d.Dispositivo).WithMany(p => p.MantenimientoCerraduras)
                .HasForeignKey(d => d.DispositivoId)
                .HasConstraintName("FK_Mantenimiento_Dispositivos");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MantenimientoCerradura> entity);
    }
}
