// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Dispositivos.Domain.Entities;

namespace Dispositivos.Persistence.Data.Configurations
{
    public partial class RegistrosAuditoriumConfiguration : IEntityTypeConfiguration<RegistrosAuditorium>
    {
        public void Configure(EntityTypeBuilder<RegistrosAuditorium> entity)
        {
            entity.HasKey(e => e.AuditoriaId);

            entity.HasIndex(e => new { e.TipoEntidad, e.EntidadId, e.FechaHora }, "IX_Auditoria_TipoEntidad").IsDescending(false, false, true);

            entity.HasIndex(e => new { e.UsuarioId, e.FechaHora }, "IX_Auditoria_UsuarioId_Fecha").IsDescending(false, true);

            entity.Property(e => e.Accion)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.AgenteUsuario).HasMaxLength(500);
            entity.Property(e => e.DireccionIp)
                .HasMaxLength(50)
                .HasColumnName("DireccionIP");
            entity.Property(e => e.FechaHora).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.MensajeError).HasMaxLength(1000);
            entity.Property(e => e.Resultado)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TipoEntidad)
                .IsRequired()
                .HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RegistrosAuditorium> entity);
    }
}
