// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Dispositivos.Domain.Entities;

namespace Dispositivos.Persistence.Data.Configurations
{
    public partial class RegistrosAccesoConfiguration : IEntityTypeConfiguration<RegistrosAcceso>
    {
        public void Configure(EntityTypeBuilder<RegistrosAcceso> entity)
        {
            entity.HasKey(e => e.RegistroId);

            entity.ToTable("RegistrosAcceso");

            entity.HasIndex(e => new { e.CerraduraId, e.FechaHoraAcceso }, "IX_RegistrosAcceso_CerraduraId_Fecha").IsDescending(false, true);

            entity.HasIndex(e => new { e.TipoAcceso, e.FechaHoraAcceso }, "IX_RegistrosAcceso_TipoAcceso").IsDescending(false, true);

            entity.HasIndex(e => new { e.UsuarioId, e.FechaHoraAcceso }, "IX_RegistrosAcceso_UsuarioId_Fecha").IsDescending(false, true);

            entity.Property(e => e.CodigoError).HasMaxLength(50);
            entity.Property(e => e.DireccionIp)
                .HasMaxLength(50)
                .HasColumnName("DireccionIP");
            entity.Property(e => e.FechaHoraAcceso).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.InfoDispositivo).HasMaxLength(500);
            entity.Property(e => e.MotivoAcceso).HasMaxLength(200);
            entity.Property(e => e.ResultadoAcceso)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TipoAcceso)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Cerradura).WithMany(p => p.RegistrosAccesos)
                .HasForeignKey(d => d.CerraduraId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RegistrosAcceso_Cerraduras");

            entity.HasOne(d => d.Credencial).WithMany(p => p.RegistrosAccesos)
                .HasForeignKey(d => d.CredencialId)
                .HasConstraintName("FK_RegistrosAcceso_Credenciales");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RegistrosAcceso> entity);
    }
}
