// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Dispositivos.Persistence.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using Dispositivos.Domain.Entities;
using System.Collections.Generic;
#nullable disable

namespace Dispositivos.Persistence.Data;

public partial class BarceloIoTDatabaseContext : DbContext
{
    public BarceloIoTDatabaseContext(DbContextOptions<BarceloIoTDatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CerradurasInteligente> CerradurasInteligentes { get; set; }

    public virtual DbSet<CredencialesAcceso> CredencialesAccesos { get; set; }

    public virtual DbSet<Dispositivo> Dispositivos { get; set; }

    public virtual DbSet<MantenimientoCerradura> MantenimientoCerraduras { get; set; }

    public virtual DbSet<RegistrosAcceso> RegistrosAccesos { get; set; }

    public virtual DbSet<RegistrosAuditorium> RegistrosAuditoria { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");

        modelBuilder.ApplyConfiguration(new Configurations.CerradurasInteligenteConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CredencialesAccesoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DispositivoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.MantenimientoCerraduraConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RegistrosAccesoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RegistrosAuditoriumConfiguration());
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
