CREATE TABLE [dbo].[CheckOuts](
	[CheckOutId]    [int] IDENTITY(1,1) NOT NULL,
	[ReservaId]     [int] NOT NULL,
	[FechaCheckOut] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_CheckOuts] PRIMARY KEY CLUSTERED
(
	[CheckOutId] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_CheckOuts_ReservaId] UNIQUE NONCLUSTERED
(
	[ReservaId] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CheckOuts] WITH CHECK ADD CONSTRAINT [FK_CheckOuts_Reservas] FOREIGN KEY([ReservaId])
REFERENCES [dbo].[Reservas] ([ReservaId])
GO

ALTER TABLE [dbo].[CheckOuts] CHECK CONSTRAINT [FK_CheckOuts_Reservas]
GO

ALTER TABLE [dbo].[CheckOuts] ADD DEFAULT (getutcdate()) FOR [FechaCheckOut]
GO

CREATE NONCLUSTERED INDEX [IX_CheckOuts_ReservaId] ON [dbo].[CheckOuts]
(
	[ReservaId] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
