CREATE TABLE [dbo].[CheckIns](
	[CheckInId]      [int] IDENTITY(1,1) NOT NULL,
	[ReservaId]      [int] NOT NULL,
	[NombreCompleto] [nvarchar](200) NOT NULL,
	[Email]          [nvarchar](200) NOT NULL,
	[Telefono]       [nvarchar](20) NOT NULL,
	[FechaCheckIn]   [datetime2](7) NOT NULL,
	[DireccionIp]    [nvarchar](45) NULL,
	[Estado]         [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_CheckIns] PRIMARY KEY CLUSTERED
(
	[CheckInId] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_CheckIns_ReservaId] UNIQUE NONCLUSTERED
(
	[ReservaId] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CheckIns] WITH CHECK ADD CONSTRAINT [FK_CheckIns_Reservas] FOREIGN KEY([ReservaId])
REFERENCES [dbo].[Reservas] ([ReservaId])
GO

ALTER TABLE [dbo].[CheckIns] CHECK CONSTRAINT [FK_CheckIns_Reservas]
GO

ALTER TABLE [dbo].[CheckIns] ADD DEFAULT (getutcdate()) FOR [FechaCheckIn]
GO

ALTER TABLE [dbo].[CheckIns] ADD DEFAULT ('Completado') FOR [Estado]
GO

CREATE NONCLUSTERED INDEX [IX_CheckIns_ReservaId] ON [dbo].[CheckIns]
(
	[ReservaId] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_CheckIns_Email] ON [dbo].[CheckIns]
(
	[Email] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
