CREATE TABLE [dbo].[Puestos](
	[PuestoId] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Descripcion] [nvarchar](500) NULL,
	[EstaActivo] [bit] NOT NULL,
	[FechaCreacion] [datetime2](7) NOT NULL,
	[EliminadoEn] [datetime2](7) NULL,
 CONSTRAINT [PK_Puestos] PRIMARY KEY CLUSTERED
(
	[PuestoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Puestos_Nombre] UNIQUE NONCLUSTERED
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Puestos] ADD  DEFAULT ((1)) FOR [EstaActivo]
GO
ALTER TABLE [dbo].[Puestos] ADD  DEFAULT (getutcdate()) FOR [FechaCreacion]
GO
