// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservas.Persistence.Data;

#nullable disable

namespace Reservas.Persistence.Migrations
{
    [DbContext(typeof(BarceloReservasContext))]
    [Migration("20260322100000_AddEstadosReservaTable")]
    partial class AddEstadosReservaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reservas.Domain.Entities.CheckIn", b =>
                {
                    b.Property<int>("CheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInId"));

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Completado");

                    b.Property<DateTime>("FechaCheckIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CheckInId");

                    b.HasIndex(new[] { "Email" }, "IX_CheckIns_Email");

                    b.HasIndex(new[] { "ReservaId" }, "IX_CheckIns_ReservaId")
                        .IsUnique();

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.EstadoReserva", b =>
                {
                    b.Property<int>("EstadoReservaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoReservaId");

                    b.ToTable("EstadosReserva");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<DateTime?>("CheckInRealizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutRealizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EstadoReservaId")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("HuespedId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("NumeroHuespedes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("NumeroNinos")
                        .HasColumnType("int");

                    b.Property<string>("NumeroReserva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ReservaId");

                    b.HasIndex(new[] { "EstadoReservaId", "FechaCheckIn", "FechaCheckOut" }, "IX_Reservas_Estado_Fechas");

                    b.HasIndex(new[] { "EstadoReservaId" }, "IX_Reservas_EstadoReservaId");

                    b.HasIndex(new[] { "HabitacionId" }, "IX_Reservas_HabitacionId");

                    b.HasIndex(new[] { "HuespedId" }, "IX_Reservas_HuespedId");

                    b.HasIndex(new[] { "NumeroReserva" }, "IX_Reservas_NumeroReserva");

                    b.HasIndex(new[] { "NumeroReserva" }, "UQ_Reservas_NumeroReserva")
                        .IsUnique();

                    b.ToTable("Reservas", t =>
                        {
                            t.HasTrigger("TRG_ActualizarEstadoHabitacion");

                            t.HasTrigger("TRG_Audit_Reservas");

                            t.HasTrigger("TRG_DesactivarCredencialesCheckout");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Reservas.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("Reservas.Domain.Entites.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.Reserva", b =>
                {
                    b.HasOne("Reservas.Domain.Entites.EstadoReserva", "EstadoReserva")
                        .WithMany("Reservas")
                        .HasForeignKey("EstadoReservaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reservas_EstadosReserva");

                    b.Navigation("EstadoReserva");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.EstadoReserva", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
