// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservas.Persistence.Data;

#nullable disable

namespace Reservas.Persistence.Migrations
{
    [DbContext(typeof(BarceloReservasContext))]
    [Migration("20260422135754_AddEstadoReservaActividadTable")]
    partial class AddEstadoReservaActividadTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reservas.Domain.Entites.ActividadesRecreativas", b =>
                {
                    b.Property<int>("ActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActividadId"));

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<TimeSpan>("HoraApertura")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImagenURL");

                    b.Property<string>("NombreActividad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioPorPersona")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("RequiereReserva")
                        .HasColumnType("bit");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ActividadId");

                    b.ToTable("ActividadesRecreativas", (string)null);
                });

            modelBuilder.Entity("Reservas.Domain.Entites.EstadoReserva", b =>
                {
                    b.Property<int>("EstadoReservaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoReservaId");

                    b.ToTable("EstadosReserva", (string)null);
                });

            modelBuilder.Entity("Reservas.Domain.Entites.EstadoReservaActividad", b =>
                {
                    b.Property<int>("EstadoReservaActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoReservaActividadId");

                    b.ToTable("EstadosReservaActividad", (string)null);
                });

            modelBuilder.Entity("Reservas.Domain.Entites.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<DateTime?>("CheckInRealizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutRealizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EstadoReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("HuespedId")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("NumeroHuespedes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("NumeroNinos")
                        .HasColumnType("int");

                    b.Property<string>("NumeroReserva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ReservaId");

                    b.HasIndex(new[] { "EstadoReservaId", "FechaCheckIn", "FechaCheckOut" }, "IX_Reservas_Estado_Fechas");

                    b.HasIndex(new[] { "HabitacionId" }, "IX_Reservas_HabitacionId");

                    b.HasIndex(new[] { "HuespedId" }, "IX_Reservas_HuespedId");

                    b.HasIndex(new[] { "NumeroReserva" }, "IX_Reservas_NumeroReserva");

                    b.HasIndex(new[] { "NumeroReserva" }, "UQ_Reservas_NumeroReserva")
                        .IsUnique();

                    b.ToTable("Reservas", t =>
                        {
                            t.HasTrigger("TRG_ActualizarEstadoHabitacion");

                            t.HasTrigger("TRG_Audit_Reservas");

                            t.HasTrigger("TRG_DesactivarCredencialesCheckout");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Reservas.Domain.Entites.ReservaHuesped", b =>
                {
                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("HuespedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("PuedeCrearActividadesRecreativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PuedeDesbloquearCerradura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ReservaId", "HuespedId");

                    b.HasIndex(new[] { "HuespedId" }, "IX_ReservaHuespedes_HuespedId");

                    b.ToTable("ReservaHuespedes");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.ReservasActividades", b =>
                {
                    b.Property<int>("ReservaActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaActividadId"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Confirmada");

                    b.Property<int>("EstadoReservaActividadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("FechaRecordatorio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("HoraReserva")
                        .HasColumnType("time");

                    b.Property<int>("HuespedId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NotasEspeciales")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumeroPersonas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("RecordatorioEnviado")
                        .HasColumnType("bit");

                    b.HasKey("ReservaActividadId");

                    b.HasIndex("ActividadId");

                    b.HasIndex("EstadoReservaActividadId");

                    b.HasIndex(new[] { "FechaReserva", "HoraReserva" }, "IX_ReservasActividades_Fecha");

                    b.HasIndex(new[] { "HuespedId" }, "IX_ReservasActividades_HuespedId");

                    b.ToTable("ReservasActividades", (string)null);
                });

            modelBuilder.Entity("Reservas.Domain.Entities.EstadoHabitacion", b =>
                {
                    b.Property<int>("EstadoHabitacionId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoHabitacionId");

                    b.ToTable("EstadosHabitacion", (string)null);
                });

            modelBuilder.Entity("Reservas.Domain.Entities.Habitacion", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HabitacionId"));

                    b.Property<int>("CapacidadMaxima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EstadoHabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroHabitacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TipoHabitacionId")
                        .HasColumnType("int");

                    b.HasKey("HabitacionId");

                    b.HasIndex("EstadoHabitacionId");

                    b.HasIndex("HotelId");

                    b.HasIndex("TipoHabitacionId");

                    b.HasIndex("HotelId", "NumeroHabitacion")
                        .IsUnique();

                    b.ToTable("Habitaciones", (string)null);
                });

            modelBuilder.Entity("Reservas.Domain.Entities.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HotelId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("NumeroEstrellas")
                        .HasColumnType("tinyint");

                    b.Property<int>("NumeroHabitaciones")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HotelId");

                    b.ToTable("Hoteles", (string)null);
                });

            modelBuilder.Entity("Reservas.Domain.Entities.TipoHabitacion", b =>
                {
                    b.Property<int>("TipoHabitacionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoHabitacionId");

                    b.ToTable("TiposHabitacion", (string)null);
                });

            modelBuilder.Entity("Reservas.Domain.Entites.Reserva", b =>
                {
                    b.HasOne("Reservas.Domain.Entites.EstadoReserva", "EstadoReserva")
                        .WithMany("Reservas")
                        .HasForeignKey("EstadoReservaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reservas_EstadosReserva");

                    b.Navigation("EstadoReserva");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.ReservaHuesped", b =>
                {
                    b.HasOne("Reservas.Domain.Entites.Reserva", "Reserva")
                        .WithMany("ReservaHuespedes")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReservaHuespedes_Reservas");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.ReservasActividades", b =>
                {
                    b.HasOne("Reservas.Domain.Entites.ActividadesRecreativas", "Actividad")
                        .WithMany("ReservasActividades")
                        .HasForeignKey("ActividadId")
                        .IsRequired()
                        .HasConstraintName("FK_ReservasActividades_Actividades");

                    b.HasOne("Reservas.Domain.Entites.EstadoReservaActividad", "EstadoReservaActividad")
                        .WithMany("ReservasActividades")
                        .HasForeignKey("EstadoReservaActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReservasActividades_EstadosReservaActividad");

                    b.Navigation("Actividad");

                    b.Navigation("EstadoReservaActividad");
                });

            modelBuilder.Entity("Reservas.Domain.Entities.Habitacion", b =>
                {
                    b.HasOne("Reservas.Domain.Entities.EstadoHabitacion", "EstadoHabitacion")
                        .WithMany("Habitaciones")
                        .HasForeignKey("EstadoHabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reservas.Domain.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reservas.Domain.Entities.TipoHabitacion", "TipoHabitacion")
                        .WithMany("Habitaciones")
                        .HasForeignKey("TipoHabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoHabitacion");

                    b.Navigation("Hotel");

                    b.Navigation("TipoHabitacion");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.ActividadesRecreativas", b =>
                {
                    b.Navigation("ReservasActividades");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.EstadoReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.EstadoReservaActividad", b =>
                {
                    b.Navigation("ReservasActividades");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.Reserva", b =>
                {
                    b.Navigation("ReservaHuespedes");
                });

            modelBuilder.Entity("Reservas.Domain.Entities.EstadoHabitacion", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("Reservas.Domain.Entities.TipoHabitacion", b =>
                {
                    b.Navigation("Habitaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
