// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservas.Persistence.Data;

#nullable disable

namespace Reservas.Persistence.Migrations
{
    [DbContext(typeof(BarceloReservasContext))]
    partial class BarceloReservasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reservas.Domain.Entites.ActividadesRecreativa", b =>
                {
                    b.Property<int>("ActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActividadId"));

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<TimeSpan>("HoraApertura")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImagenURL");

                    b.Property<string>("NombreActividad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioPorPersona")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("RequiereReserva")
                        .HasColumnType("bit");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ActividadId");

                    b.ToTable("ActividadesRecreativas");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<DateTime?>("CheckInRealizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutRealizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("HuespedId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("NumeroHuespedes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("NumeroNinos")
                        .HasColumnType("int");

                    b.Property<string>("NumeroReserva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ReservaId");

                    b.HasIndex(new[] { "Estado", "FechaCheckIn", "FechaCheckOut" }, "IX_Reservas_Estado_Fechas");

                    b.HasIndex(new[] { "HabitacionId" }, "IX_Reservas_HabitacionId");

                    b.HasIndex(new[] { "HuespedId" }, "IX_Reservas_HuespedId");

                    b.HasIndex(new[] { "NumeroReserva" }, "IX_Reservas_NumeroReserva");

                    b.HasIndex(new[] { "NumeroReserva" }, "UQ_Reservas_NumeroReserva")
                        .IsUnique();

                    b.ToTable("Reservas", t =>
                        {
                            t.HasTrigger("TRG_ActualizarEstadoHabitacion");

                            t.HasTrigger("TRG_Audit_Reservas");

                            t.HasTrigger("TRG_DesactivarCredencialesCheckout");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Reservas.Domain.Entites.ReservasActividade", b =>
                {
                    b.Property<int>("ReservaActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaActividadId"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Confirmada");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("FechaRecordatorio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("HoraReserva")
                        .HasColumnType("time");

                    b.Property<int>("HuespedId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NotasEspeciales")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumeroPersonas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("RecordatorioEnviado")
                        .HasColumnType("bit");

                    b.HasKey("ReservaActividadId");

                    b.HasIndex("ActividadId");

                    b.HasIndex(new[] { "FechaReserva", "HoraReserva" }, "IX_ReservasActividades_Fecha");

                    b.HasIndex(new[] { "HuespedId" }, "IX_ReservasActividades_HuespedId");

                    b.ToTable("ReservasActividades");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.ReservasActividade", b =>
                {
                    b.HasOne("Reservas.Domain.Entites.ActividadesRecreativa", "Actividad")
                        .WithMany("ReservasActividades")
                        .HasForeignKey("ActividadId")
                        .IsRequired()
                        .HasConstraintName("FK_ReservasActividades_Actividades");

                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("Reservas.Domain.Entites.ActividadesRecreativa", b =>
                {
                    b.Navigation("ReservasActividades");
                });
#pragma warning restore 612, 618
        }
    }
}
