// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Usuarios.Domain.Entities;

namespace Usuarios.Persistence.Data;

public partial class BarceloIoTSystemContext : DbContext
{
    public BarceloIoTSystemContext(DbContextOptions<BarceloIoTSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Huespede> Huespedes { get; set; }

    public virtual DbSet<PermisosPersonal> PermisosPersonals { get; set; }

    public virtual DbSet<Personal> Personals { get; set; }

    public virtual DbSet<HabitacionLookup> Habitaciones { get; set; }

    public virtual DbSet<ActividadLookup> ActividadesRecreativas { get; set; }

    public virtual DbSet<UsuarioLookup> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Huespede>(entity =>
        {
            entity.HasKey(e => e.HuespedId);

            entity.HasIndex(e => new { e.TipoDocumento, e.NumeroDocumento }, "UQ_Huespedes_Documento").IsUnique();

            entity.HasIndex(e => e.UsuarioId, "UQ_Huespedes_Usuario").IsUnique();

            entity.Property(e => e.ContactoEmergencia).HasMaxLength(200);
            entity.Property(e => e.EsVip).HasColumnName("EsVIP");
            entity.Property(e => e.FechaNacimiento).HasColumnType("date");
            entity.Property(e => e.FechaRegistro).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Nacionalidad)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NombreCompleto)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NotasEspeciales).HasMaxLength(1000);
            entity.Property(e => e.NumeroDocumento)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PreferenciasAlimentarias).HasMaxLength(500);
            entity.Property(e => e.TelefonoEmergencia).HasMaxLength(50);
            entity.Property(e => e.TipoDocumento)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UsuarioId).IsRequired();
        });

        modelBuilder.Entity<PermisosPersonal>(entity =>
        {
            entity.HasKey(e => e.PermisoId);

            entity.ToTable("PermisosPersonal");

            entity.Property(e => e.EstaActivo).HasDefaultValue(true);
            entity.Property(e => e.FechaOtorgamiento).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Justificacion).HasMaxLength(500);
            entity.Property(e => e.OtorgadoPor)
                .IsRequired()
                .HasMaxLength(450);

            entity.HasOne(d => d.Personal).WithMany(p => p.PermisosPersonals)
                .HasForeignKey(d => d.PersonalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PermisosPersonal_Personal");

            // FK a Habitaciones (tabla de Reservas, misma DB)
            entity.Property(e => e.HabitacionId).IsRequired(false);
            entity.HasIndex(e => e.HabitacionId).HasDatabaseName("IX_PermisosPersonal_HabitacionId");
            entity.HasOne(d => d.Habitacion)
                .WithMany()
                .HasForeignKey(d => d.HabitacionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PermisosPersonal_Habitaciones");

            // FK a ActividadesRecreativas (tabla de Reservas, misma DB)
            entity.Property(e => e.ActividadId).IsRequired(false);
            entity.HasIndex(e => e.ActividadId).HasDatabaseName("IX_PermisosPersonal_ActividadId");
            entity.HasOne(d => d.Actividad)
                .WithMany()
                .HasForeignKey(d => d.ActividadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PermisosPersonal_ActividadesRecreativas");

            // FK a Users (tabla de Identity, misma DB)
            entity.HasOne(d => d.OtorgadoPorNavigation)
                .WithMany()
                .HasForeignKey(d => d.OtorgadoPor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PermisosPersonal_OtorgadoPor");
        });

        modelBuilder.Entity<Personal>(entity =>
        {
            entity.ToTable("Personal");

            entity.HasIndex(e => e.NumeroEmpleado, "UQ_Personal_NumeroEmpleado").IsUnique();

            entity.HasIndex(e => e.UsuarioId, "UQ_Personal_Usuario").IsUnique();

            entity.Property(e => e.Departamento)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.EstaActivo).HasDefaultValue(true);
            entity.Property(e => e.FechaContratacion).HasColumnType("date");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.NombreCompleto)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NumeroEmpleado)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Puesto)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Turno).HasMaxLength(20);
            entity.Property(e => e.UsuarioId).IsRequired();

            entity.HasOne(d => d.SupervisorNavigation).WithMany(p => p.InverseSupervisorNavigation)
                .HasForeignKey(d => d.Supervisor)
                .HasConstraintName("FK_Personal_Supervisor");
        });

        modelBuilder.Entity<HabitacionLookup>(entity =>
        {
            entity.HasKey(e => e.HabitacionId);
            entity.ToTable("Habitaciones");
            entity.Property(e => e.NumeroHabitacion).IsRequired().HasMaxLength(20);
        });

        modelBuilder.Entity<ActividadLookup>(entity =>
        {
            entity.HasKey(e => e.ActividadId);
            entity.ToTable("ActividadesRecreativas");
            entity.Property(e => e.NombreActividad).IsRequired().HasMaxLength(200);
        });

        modelBuilder.Entity<UsuarioLookup>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.ToTable("Users");
            entity.Property(e => e.UserName).HasMaxLength(256);
            entity.Property(e => e.Email).HasMaxLength(256);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}