// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dispositivos.Domain.Entities;

public partial class CerradurasInteligente
{
    public int CerraduraId { get; set; }

    public int DispositivoId { get; set; }

    public int HabitacionId { get; set; }

    public string EstadoPuerta { get; set; }

    public DateTime? UltimaApertura { get; set; }

    public int ContadorAperturas { get; set; }

    public bool SoportaModoOffline { get; set; }

    public DateTime FechaActivacion { get; set; }

    public bool EstaActiva { get; set; }

    public virtual Dispositivo Dispositivo { get; set; }

    public virtual ICollection<MantenimientoCerradura> MantenimientoCerraduras { get; set; } = new List<MantenimientoCerradura>();

    public virtual ICollection<RegistrosAcceso> RegistrosAccesos { get; set; } = new List<RegistrosAcceso>();
}