// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dispositivos.Domain.Entities;

public partial class CredencialesAcceso
{
    public int CredencialId { get; set; }

    public int? HuespedId { get; set; }

    public int? PersonalId { get; set; }

    public string CodigoPin { get; set; }

    public string HashPin { get; set; }

    public DateTime FechaActivacion { get; set; }

    public DateTime FechaExpiracion { get; set; }

    public bool EstaActiva { get; set; }

    public string TipoCredencial { get; set; }

    public DateTime FechaCreacion { get; set; }

    public string CreadoPor { get; set; }

    public int NumeroUsos { get; set; }

    public DateTime? UltimoUso { get; set; }

    public virtual ICollection<RegistrosAcceso> RegistrosAccesos { get; set; } = new List<RegistrosAcceso>();
}