// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dispositivos.Domain.Entities;

public partial class Dispositivo
{
    public Guid DispositivoId { get; set; }

    public int HotelId { get; set; }

    public string NumeroSerieDispositivo { get; set; }

    public string DireccionMac { get; set; }

    public string TipoDispositivo { get; set; }

    public string Modelo { get; set; }

    public string VersionFirmware { get; set; }

    public int NivelBateria { get; set; }

    public bool EstaEnLinea { get; set; }

    public DateTime? UltimaSincronizacion { get; set; }

    public DateTime FechaInstalacion { get; set; }

    public string EstadoFuncional { get; set; }

    public DateTime? UltimaActualizacionFirmware { get; set; }

    public string Ipdispositivo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual ICollection<CerradurasInteligente> CerradurasInteligentes { get; set; } = new List<CerradurasInteligente>();

    public virtual ICollection<MantenimientoCerradura> MantenimientoCerraduras { get; set; } = new List<MantenimientoCerradura>();
}