// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dispositivos.Domain.Entities;

public partial class MantenimientoCerradura
{
    public int MantenimientoId { get; set; }

    public Guid? DispositivoId { get; set; }

    public int? CerraduraId { get; set; }

    public string TipoMantenimiento { get; set; }

    public DateTime FechaProgramada { get; set; }

    public DateTime? FechaRealizada { get; set; }

    public int? PersonalId { get; set; }

    public string Estado { get; set; }

    public string Observaciones { get; set; }

    public decimal? CostoMantenimiento { get; set; }

    public int? TiempoEmpleadoMinutos { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual CerradurasInteligente Cerradura { get; set; }

    public virtual Dispositivo Dispositivo { get; set; }
}