// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dispositivos.Domain.Entities;

public partial class RegistrosAuditorium
{
    public long AuditoriaId { get; set; }

    public string UsuarioId { get; set; }

    public string Accion { get; set; }

    public string TipoEntidad { get; set; }

    public int? EntidadId { get; set; }

    public string ValorAnterior { get; set; }

    public string ValorNuevo { get; set; }

    public DateTime FechaHora { get; set; }

    public string DireccionIp { get; set; }

    public string AgenteUsuario { get; set; }

    public string Resultado { get; set; }

    public string MensajeError { get; set; }

    public int? HotelId { get; set; }
}