// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dispositivos.Domain.Entities;

public partial class RegistrosAcceso
{
    public long RegistroId { get; set; }

    public int CerraduraId { get; set; }

    public int? CredencialId { get; set; }

    public string UsuarioId { get; set; }

    public DateTime FechaHoraAcceso { get; set; }

    public string TipoAcceso { get; set; }

    public string ResultadoAcceso { get; set; }

    public string MotivoAcceso { get; set; }

    public string DireccionIp { get; set; }

    public string InfoDispositivo { get; set; }

    public bool FueExitoso { get; set; }

    public string CodigoError { get; set; }

    public int? Latencia { get; set; }

    public virtual CerradurasInteligente Cerradura { get; set; }

    public virtual CredencialesAcceso Credencial { get; set; }
}