// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservas.Domain.Entites;

public partial class ActividadesRecreativas
{
    public int ActividadId { get; set; }

    public int HotelId { get; set; }

    public string NombreActividad { get; set; }

    public string Descripcion { get; set; }

    public string Categoria { get; set; }

    public string Ubicacion { get; set; }

    public TimeSpan HoraApertura { get; set; }

    public TimeSpan HoraCierre { get; set; }

    public int CapacidadMaxima { get; set; }

    public decimal PrecioPorPersona { get; set; }

    public bool RequiereReserva { get; set; }

    public int? DuracionMinutos { get; set; }

    public bool EstaActiva { get; set; }

    public string ImagenUrl { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual ICollection<ReservasActividades> ReservasActividades { get; set; } = new List<ReservasActividades>();
}