// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservas.Domain.Entites;

public partial class ReservasActividade
{
    public int ReservaActividadId { get; set; }

    public int ActividadId { get; set; }

    public int HuespedId { get; set; }

    public DateTime FechaReserva { get; set; }

    public TimeSpan HoraReserva { get; set; }

    public int NumeroPersonas { get; set; }

    public string Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public decimal MontoTotal { get; set; }

    public string NotasEspeciales { get; set; }

    public bool RecordatorioEnviado { get; set; }

    public DateTime? FechaRecordatorio { get; set; }

    public virtual ActividadesRecreativa Actividad { get; set; }
}