// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservas.Domain.Entites;

public partial class Reserva
{
    public int ReservaId { get; set; }

    public int HuespedId { get; set; }

    public int HabitacionId { get; set; }

    public string NumeroReserva { get; set; }

    public DateTime FechaCheckIn { get; set; }

    public DateTime FechaCheckOut { get; set; }

    public int NumeroHuespedes { get; set; }

    public int NumeroNinos { get; set; }

    public decimal MontoTotal { get; set; }

    public decimal MontoPagado { get; set; }

    public string Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public DateTime? CheckInRealizado { get; set; }

    public DateTime? CheckOutRealizado { get; set; }

    public string CreadoPor { get; set; }

    public string Observaciones { get; set; }
}